PRIMARY_KEY = 'RINPERSOON'
#MUNICIPALIY = 'municipality'
GENDER = 'gender'
BIRTH_MONTH = 'birth_month'
BIRTH_YEAR = 'birth_year'
DAYS_SINCE_FIRST = 'days_since_first'
AGE = 'age'
ORIGIN = 'birth_municipality'
TIME_COLUMNS = [AGE, DAYS_SINCE_FIRST, 'year', 'month']
IGNORE_COLUMNS = ['educDet', 'incomeYearly', 'inc'] 
DELIMITER = ','
MISSING = 'MISSING'
FIRST_EVENT_TIME = "FIRST_EVENT_TIME"